name: C++ CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y cmake g++ make clang clang-tidy

    - name: Run Clang-Tidy
      run: |
        mkdir -p build
        cd build
        cmake ..
        run-clang-tidy

    - name: Build project
      run: make build

    - name: Run tests
      run: make test
